export enum AjusteGeralEnum {
    ALERTA_EMAIL = 'ALERTA-EMAIL-NOVA-CIDADE',
    JANELA_SIG = 'JANELA-ABERTURA-SIG-TEXTO',
    TELEFONE_ALERTA = 'TELEFONE-ALERTA-BLOQUEIO-CARTA',
    EMAIL_PLANO_METAS = 'EMAIL-ALERTA-PLANO-METAS'
}